### ISSUE TITLE
Crash / Memory error?

### ISSUE THREAD

**Issue by cyberluke** [marco-sacchi/RLoader#10]
330 items, BMP folder is 24MB => it will crash. Is my LIST.TXT badly formatted or what is happening? I'm running inside DosBox just to test it now. Example list is working.

[LIST.TXT](https://github.com/marco-sacchi/RLoader/files/6780318/LIST.TXT)

**Comment by cyberluke** [comment]
``` Type=0x4d(M) Seg=0x072f size=0x009a name='COMMAND'                              Type=0x4d(M) Seg=0x07ca size=0x0045 name='COMMAND'                              Type=0x4d(M) Seg=0x0810 size=0x1010 name='RLOADER'                              Type=0x4d(M) Seg=0x1821 size=0x0045 name='RLOADER'                              Type=0x4d(M) Seg=0x1867 size=0x1880 name='UI'                                  FINAL: Type=0x23(#) Seg=0x30e8 size=0x2120 name='^C^B^B^C^B^B^C^B'              End dump                                                                        DOS fatal memory error: Corrupt MCB chain                                       Starting debugger. ```

**Comment by cyberluke** [comment]
![garbage](https://user-images.githubusercontent.com/1111375/124837587-63074f80-df85-11eb-8cc2-d84fe0043daa.jpg)

**Comment by cyberluke** [comment]
File has only two items and is converted to ASCII, DOS encoding, codepage 852 (central european). The behavior is the same as with UTF-8. But I was able to catch extra information (happen also before but I did not have time to printscreen). Why it says CYCLES file not found?

![bad](https://user-images.githubusercontent.com/1111375/124957416-5a605900-e019-11eb-8253-ad62155c4a64.jpg)

**Comment by cyberluke** [comment]
Ok, install.exe (F5 key) will run. Game will not run because of not enough free memory under DOSBOX-X.

**Comment by cyberluke** [comment]
![memory](https://user-images.githubusercontent.com/1111375/124958030-00ac5e80-e01a-11eb-8335-15cacebdac61.jpg)

Does it mean RLOADER eat 15kb or 35kb of conventional memory? I was thinking it is not resident...this way none of DOS game will run.

**Comment by cyberluke** [comment]
The problem seems to be & character. But even I convert to OEM-US encoding, it will crash.

Second problem is the memory issue here.

Third problem is that now it did load with 325 entries, but it freeze. Cannot even F10. LIST.TXT is 18kb + BMP images (24MB). Is it some problem with parsing? Waiting 5 minutes and it did not load.

This seems like a very buggy untested software. I spent 5 days already on this. I think I will need to move on if these basic issues are not solved.

**Comment by cyberluke** [comment]
The freeze (third problem) does not happen in text mode. Perhaps it is something with loading 320 BMP files at once from the LIST.TXT? It should load max. ten for the current menu view.

**Comment by marco-sacchi** [comment]
> 330 items, BMP folder is 24MB => it will crash. Is my LIST.TXT badly formatted or what is happening? I'm running inside DosBox just to test it now. Example list is working.
> 
> [LIST.TXT](https://github.com/marco-sacchi/RLoader/files/6780318/LIST.TXT)

I copy-pasted your list in my development VM and in DOSBox ECE r4444 and vanilla DOSBox 0.74-3, in all cases it loads correctly, without any kind of error (except for the notification that the thumbnail is not available) and I can navigate and search the list.

The size of the BMP folder doesn't matter, only one thumbnail is loaded into RAM at a time.

![image](https://user-images.githubusercontent.com/81907055/125170514-a9d88d80-e1af-11eb-9e99-62e773739c99.png)

Attach some thumbnails so that I can check if there are compatibility problems with the bmp files generated by your tools.

> File has only two items and is converted to ASCII, DOS encoding, codepage 852 (central european). The behavior is the same as with UTF-8. But I was able to catch extra information (happen also before but I did not have time to printscreen). Why it says CYCLES file not found?

As previously explained in private UTF-8 and ASCII (of any codepage) overlap for the first 256 characters and there can be no compatibility problems even using extended characters (more than one byte per codepoint), the result would be only non-matching characters like in mismatching encodings under any system.

`cycles` is a DOSBox command, which obviously is not present in DOSBox-X, which allows the setting of emulation cycles from the command line and is used by RLoader to set the cycles specified in the LIST.TXT file for you before loading the program.

> Does it mean RLOADER eat 55kb or 85kb of conventional memory? I was thinking it is not resident...this way none of DOS game will run.

No, RLoader only takes about 11kb of ram plus the ram reserved by the operating system to run the dynamically generated batch file to launch the configuration / installation file or the program / game. This is why it is split into two .exe files. Only `rloader.exe` remains resident in RAM, ui.exe does not.

> The problem seems to be & character. But even I convert to OEM-US encoding, it will crash.

![image](https://user-images.githubusercontent.com/81907055/125170975-03da5280-e1b2-11eb-90e2-7ee587263fc9.png)

> Third problem is that now it did load with 325 entries, but it freeze. Cannot even F10. LIST.TXT is 18kb + BMP images (24MB). Is it some problem with parsing? Waiting 5 minutes and it did not load.

I have never encountered such problems, please attach all necessary files when you encounter a problem, otherwise it is impossible for me to reproduce or verify.

> This seems like a very buggy untested software. I spent 5 days already on this. I think I will need to move on if these basic issues are not solved.

I personally test every single line of code I write, both when I do it for work and when I do it as a hobby.

Labeling the software as very buggy and untested without re-checking what you entered in RLoader (LIST.TXT file or thumbnails) or if in doubt, downloading the source, reviewing it and possibly compiling and testing it yourself is at least offensive.

> EDIT2: The problem was faulty BMP with bit depth 24 instead of 4. It will freeze and crash. But I used same command imagemagick for all images. Will re-code images.

I'll add a check to verify that the thumbnails are indeed 4bit-per-pixel bitmaps.

> The example command you send me and I converted it to batch script is missing parameter: -depth 4

This is really weird, I checked that command line with a couple of png images I had and all of them were generated with 4bits color depth, maybe we have different imagemagick versions (I have this: `ImageMagick-7.1.0-2-portable-Q8-x64`)

I leave this issue open for a few days to give you the possibility to reply if you want.

**Comment by cyberluke** [comment]
Hello, the main issue was the imagemagick command. I downloaded the latest version imageMagick-7.1.0-2-Q16-HDRI-x64-dll.exe

After supplying all the parameters including 4bit per pixel bitmap, it works.
